[package]
name = "battlers"
version = "2.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
rand = "0.9.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
